# Generated by Django 2.2.16 on 2023-01-18 15:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('title',
                 models.CharField(max_length=200, verbose_name='Имя группы')),
                ('slug', models.SlugField(max_length=100, unique=True,
                                          verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст нового поста',
                                          validators=[
                                              django.core.validators.MinLengthValidator(
                                                  5,
                                                  'Пост должен содержать не менее 5 символов')],
                                          verbose_name='Текст поста')),
                ('pub_date',
                 models.DateTimeField(auto_now_add=True, db_index=True,
                                      verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, upload_to='posts/',
                                            verbose_name='Картинка')),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='posts', to=settings.AUTH_USER_MODEL,
                    verbose_name='Автор')),
                ('group', models.ForeignKey(blank=True,
                                            help_text='Группа, к которой будет относиться пост',
                                            max_length=200, null=True,
                                            on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='posts',
                                            to='posts.Group',
                                            verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='following', to=settings.AUTH_USER_MODEL,
                    verbose_name='Автор комментария')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='follower', to=settings.AUTH_USER_MODEL,
                    verbose_name='Автор комментария')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('text',
                 models.TextField(help_text='Текст нового комментария',
                                  validators=[
                                      django.core.validators.MinLengthValidator(
                                          5,
                                          'Комментарий должен содержать не менее 5 символов')],
                                  verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True,
                                                 verbose_name='Дата публикации')),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments', to=settings.AUTH_USER_MODEL,
                    verbose_name='Автор комментария')),
                ('post', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments', to='posts.Post',
                    verbose_name='Связанный комментарий')),
            ],
        ),
    ]
